<%@ Page Language="C#" AutoEventWireup="true" CodeFile="DirectoryManage.aspx.cs" Inherits="Portal_DirectoryManage" StylesheetTheme="Web2ASPNET2" %>
<%@ Register Src="../UserControl/ModuleTitle.ascx" TagName="ModuleTitle" TagPrefix="ucTitle" %>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>无标题页</title>    
</head>
<body style="margin:0;border:0" class="Body">
    <form id="form1" runat="server">    
    <table class="Table" cellpadding="2" cellspacing="0" border="1" bordercolor="#daeeee">
		<tr>
			<td colspan="2"><ucTitle:ModuleTitle ID="ModuleTitle1" runat="server" Title="管理网络存储的目录" /></td>
		</tr>		
		<tr>
			<td colspan="2" valign="top" bgcolor="#184073">
				<asp:TreeView ID="tvDirectory" runat="server" SkinID="tvSkin" Width="100%" Height="100%" ImageSet="Msdn" NodeIndent="10" PopulateNodesFromClient="False" AutoGenerateDataBindings="False" EnableClientScript="False">					
				</asp:TreeView>
			</td>
		</tr>			
		<tr>
			<td width="150" height="30" valign="middle" class="LeftTD" align="right">
				<asp:Label ID="Label1" runat="server" Width="150px"></asp:Label></td>
			<td valign="middle" width="100%">
				<asp:Button ID="btnAdd" runat="server" Text="添加新的目录" CssClass="Button" SkinID="btnSkin" CommandName="add" OnCommand="btn_Command" />&nbsp;&nbsp;&nbsp;
				<asp:Button ID="btnUpdate" runat="server" Text="修改目录的属性" CssClass="Button" SkinID="btnSkin" CommandName="update" OnCommand="btn_Command" />&nbsp;&nbsp;&nbsp;
				<asp:Button ID="btnDelete" runat="server" Text="删除目录" CssClass="Button" SkinID="btnSkin" CommandName="delete" OnCommand="btn_Command" />&nbsp;&nbsp;&nbsp;
				<asp:Button ID="btnAddDocument" runat="server" Text="添加新的文档" CssClass="Button" SkinID="btnSkin" CommandName="adddoc" OnCommand="btn_Command" />
			</td>
		</tr>
    </table>    
    </form>
</body>
</html>
