<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ViewDirectory.aspx.cs" Inherits="Portal_ViewDirectory" StylesheetTheme="Web2ASPNET2" %>
<%@ Register Src="../UserControl/ModuleTitle.ascx" TagName="ModuleTitle" TagPrefix="ucTitle" %>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>无标题页</title>    
</head>
<body style="margin:0;border:0" class="Body">
    <form id="form1" runat="server">    
    <table class="Table" cellpadding="2" cellspacing="0" border="1" bordercolor="#daeeee">
		<tr>
			<td colspan="2"><ucTitle:ModuleTitle ID="ModuleTitle1" runat="server" Title="以树型形式查看目录及其文档" /></td>
		</tr>		
		<tr>
			<td colspan="2" valign="top" bgcolor="#184073">
				<asp:TreeView ID="tvDirectory" runat="server" SkinID="tvSkin" Width="100%" Height="100%" ImageSet="Msdn" NodeIndent="10" PopulateNodesFromClient="False" AutoGenerateDataBindings="False" EnableClientScript="False">					
				</asp:TreeView>
			</td>
		</tr>			
		<tr>
			<td width="150" height="30" valign="middle" class="LeftTD" align="right">
				<asp:Label ID="Label1" runat="server" Width="150px"></asp:Label></td>
			<td valign="middle" width="100%">
				<asp:Button ID="btnAdd" runat="server" Text="添加新的文档" CssClass="Button" OnClick="btnAdd_Click" SkinID="btnSkin" /></td>
		</tr>
    </table>    
    </form>
</body>
</html>

