using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

public partial class PersonalArea_ViewTodayTask : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        //获取当前登录的用户名
        HiddenField1.Value = HttpContext.Current.User.Identity.Name;

        //获取个性化设置
        GridView1.GridLines = Profile.GridLine;
        //是否支持删除操作
        GridView1.AutoGenerateDeleteButton = Profile.EditSet.EnableDelete;
    }
}
